from ui.project import qiqiao
from selenium import webdriver

driver = webdriver.Chrome(executable_path="D:\Projects\MagicAutoTestFranmework\\ui\driver\chromedriver.exe")
qiqiao.public(driver).loginRuntime()
# qiqiao.public(driver).openAppPage()
# qiqiao.public(driver).clickApp("自动化应用（勿删）")
qiqiao.public(driver).clickLeftMenu("主表")
qiqiao.public(driver).clickButtonInTitle("添加")
qiqiao.singleLineText(driver).sendValue("单行文本","自动化测试")
qiqiao.multilineText(driver).sendValue("多行文本","多行文本测试")
qiqiao.number(driver).sendValue("数字",12)
qiqiao.singleChoice(driver).sendValue("单项选择",1)
qiqiao.singleChoice(driver).dropDown("单项下拉","北京")
qiqiao.multipleChoice(driver).checked("多项选择",1,2)
qiqiao.multipleChoice(driver).dropDown("多项下拉","宝马X3","宝马X5","奔驰S600","奥迪A6")
qiqiao.date(driver).sendValue("日期","2020-09-28")
qiqiao.time(driver).sendValue("时间","07:15")
qiqiao.dateTime(driver).sendValue("日期时间","2020-09-28 00:00")
qiqiao.personSelector(driver).sendValue("人员单选","刁惠云")
qiqiao.multiplePerson(driver).sendValue("人员多选","刁惠云","罗琳月")