ui:
  OA:
    case_path: oa_system
    report_file_name: OA应用测试报告
    log_file_name: 日志文件
    output_path: path
    title: OA系统
    description: OA应用自动化冒烟测试
    thread_count: 1
    thread_start_wait: 0
    sequential_execution: False
    lang: cn

  do1Values:
    case_path: do1_values
    report_file_name: 道一价值观测试报告
    log_file_name: 日志文件
    output_path: path
    title: OA系统
    description: 道一云价值观冒烟测试
    thread_count: 1
    thread_start_wait: 0
    sequential_execution: False
    lang: cn